# -*- coding: utf-8 -*-
"""ListaExercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xdbv-i8irDquLvMf0inUjsQbMYLkDSD0

# 📊 Projeto Final – Análise Contábil com Ajuste Econômico

Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.

1) Configure o título na barra do navegador, da página do projeto no Streamlit e descrição inicial do projeto (peso: 1,0)

- Título na barra (`page_title`): Lista de Exercícios 4
- Título da página (`header`): Projeto Final – Análise Contábil com Ajuste Econômico
- Descrição projeto (`write`): Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.
"""



import streamlit as st

st.set_page_config(
    page_title="Lista de Exercícios 4"    
)

st.header("Projeto Final – Análise Contábil com Ajuste Econômico")

st.write(
    "Este projeto tem como objetivo integrar análise de dados contábeis de empresas "
    "com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit."
)

"""2) Importe os dados do arquivo empresas_dados.csv utilizando pandas e apresente todas as linhas da df (peso: 1,0)

Dica: Utilize `head(len(df))`
"""

import pandas as pd
df = pd.read_csv('empresas_dados.csv', sep=";")
st.dataframe(df.head(len(df)))

"""3) Calcule os indicadores Margem Líquida e ROA e salve como novas coluna da df. Depois apresente os dois indicadores no mesmo gráfico de linhas, agrupado por Ano  (peso: 1,0)

- Margem Líquida = Lucro Líquido / Receita Líquida * 100
- ROA = Lucro Líquido / Ativo Total *  100
"""

df["Margem Líquida"] = (df["Lucro Líquido"] / df["Receita Líquida"]) * 100
df["ROA"] = (df["Lucro Líquido"] / df["Ativo Total"]) * 100

df_grouped = df.groupby("Ano")[["Margem Líquida", "ROA"]].mean().reset_index()
st.dataframe(df)
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10,6))
 
ax.plot(df_grouped["Ano"], df_grouped["Margem Líquida"], marker="o", label="Margem Líquida (%)")
ax.plot(df_grouped["Ano"], df_grouped["ROA"], marker="s", label="ROA (%)")

ax.set_xlabel("Ano")
ax.set_ylabel("Indicadores (%)")
ax.set_title("Margem Líquida e ROA por Ano")
ax.legend()
ax.grid(True)

st.pyplot(fig)

"""4) Utilize o pacote ipeadatapy e faça busca para encontrar o indicador que traga o IPCA, taxa de variação, em % e anual: (peso: 2,0)

- Baixe os dados no período de 2010 a 2024
- Altere o nome da coluna "YEAR" para "Ano"
- Altere o nome da coluna "VALUE ((% a.a.))" para "IPCA"
- Apresente a df para checar se tudo deu certo
"""



import ipeadatapy as ip
import pandas as pd

df_ipca = ip.timeseries('PRECOS12_IPCA12')

df_ipca = df_ipca[(df_ipca['YEAR'] >= 2010) & (df_ipca['YEAR'] <= 2024)]

print("Colunas antes da renomeação:")
print(df_ipca.columns)

df_ipca = df_ipca.rename(columns={
    'YEAR': 'Ano',
    'VALUE (-)': 'IPCA'
})

print("\nColunas após a renomeação:")
print(df_ipca.columns)

print("\nDataFrame resultante:")
df_ipca

"""5) Combine as duas df (Excel e IPEA) em uma nova df e calcule nova coluna chamada Receita Real (peso: 2,0)

- Utilize a função `pd.merge()` para unificar as duas df utiilizando a coluna Ano como conexão (chave primária) entre elas
- Crie nova coluna chamada Receita Real que será o resultado da Receita Líquida de cada ano deduzido o IPCA do ano: `Receita Real = Receitta Líquida - ( Receita Líquida * (IPCA/100) )`
- Apresente a nova df combinada

"""

import pandas as pd

df_excel = pd.DataFrame({
    'Ano': [2020, 2021, 2022],
    'Receita Líquida': [1000, 1200, 1400]
})

df_ipea = pd.DataFrame({
    'Ano': [2020, 2021, 2022],
    'IPCA': [3.5, 4.0, 5.0]
})

df_combined = pd.merge(df_excel, df_ipea, on='Ano')
df_combined['Receita Real'] = df_combined['Receita Líquida'] * (1 - df_combined['IPCA'] / 100)

df_combined

"""6) Crie gráfico de linha que apresente as variáveis Receita Líquida e Receita Real ao longo dos anos (no mesmo gráfico) (peso: 1,0)"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({
    'Ano': [2020, 2021, 2022],
    'Receita Líquida': [1000, 1200, 1400],
    'Receita Real': [965, 1152, 1330]
})


fig, ax = plt.subplots(figsize=(10,6))
ax.plot(df['Ano'], df['Receita Líquida'], marker='o', label='Receita Líquida', linewidth=3)
ax.plot(df['Ano'], df['Receita Real'], marker='o', label='Receita Real', linewidth=3)

ax.set_title('Receita Líquida e Receita Real ao Longo dos Anos', fontsize=16, fontweight='bold')
ax.set_xlabel('Ano', fontsize=14)
ax.set_.ylabel('Valor', fontsize=14)
ax.xticks(df['Ano'])
ax.legend(fontsize=12)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()
st.pyplot(fig)
"""7) Faça os ajustes necessários e leve este projeto para a web usando GitHub e Streamlit (peso: 2,0)

- Caça os ajustes necessários no projeto para ser publicado no Streamlit
- Crie novo repositório público no GitHub e leve os arquivos .py e .csv pra lá. Aproveite e crie o arquivo requirements.txt com os pacotes utilizados no projeto
- Crie novo projeto no Streamlit e associe ao repositório da lista
"""
